#properties file for activating H2 properties (no setup required)

# H2 database configuration
spring.datasource.url=jdbc:h2:mem:patient-inMem-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=db
spring.datasource.password=

# H2 console configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
